#datatype in numpy: ndarray - n(number of),d(dimensions)
#in numpy, list is called as array
#numpy contains almost 400 methods
#shape= no.of rows,no.of columns.ex:(2,3)
#size=no.of rows*no.of columns.ex:2*3=6
#in ndarray default datatype is float

In [7]:
!pip install numpy


Defaulting to user installation because normal site-packages is not writeable


In [1]:
import numpy as np
n=np.array([1,2,3,4])    #np-libraries,array-function
print(n)
print(type(n))

[1 2 3 4]
<class 'numpy.ndarray'>


In [3]:
n2=np.array([[1,2,3],[6,5,4]])
print(n2)

[[1 2 3]
 [6 5 4]]


In [4]:
print(n.ndim,n2.ndim)
print(n.shape,n2.shape)
print(n.size,n2.size)

1 2
(4,) (2, 3)
4 6


In [6]:
import numpy as np
a=np.array([1,2,3,4])      #1D
z=np.zeros((2,3),dtype=int)          #shape is mostly a tuple
print(z)

[[0 0 0]
 [0 0 0]]


In [4]:
ones=np.ones((5,5))
print(ones)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [7]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [8]:
np.random.random((3,3))

array([[0.3715076 , 0.48358679, 0.41397547],
       [0.12457276, 0.31365633, 0.85853069],
       [0.81135975, 0.6019562 , 0.51139282]])

In [9]:
np.random.random((3,3))

array([[0.22678516, 0.93304021, 0.55865948],
       [0.14294139, 0.35924776, 0.59534329],
       [0.04572461, 0.76005696, 0.89700165]])

In [11]:
np.random.randint(1,11,(55))

array([ 3,  6,  1,  7,  9,  6,  9,  7,  2,  8,  4,  9,  9,  7,  5,  6, 10,
        9, 10,  9,  5,  2,  5,  2,  4,  3,  6,  9,  9,  8,  4,  3,  3,  9,
        5,  2,  7, 10, 10,  9,  6,  6,  7,  3,  1,  5,  3, 10,  3, 10,  3,
       10,  6,  8,  9], dtype=int32)

In [ ]:
a=np.array([1,2,3])
b=np.array([2,5,10])
c=a+b
print(c)


[ 3  7 13]


In [17]:
d=a-b
c=a*b    #element was multiplication
d=a**b
print(a)
print(b)
print(c)
print(d)

[1 2 3]
[ 2  5 10]
[ 2 10 30]
[    1    32 59049]


In [ ]:
print(np.sin(a))          #np-library,sin-function
print(np.cos(a))
print(np.tan(b))
print(a.mean())           #a-variable,mean-method

[0.84147098 0.90929743 0.14112001]
[ 0.54030231 -0.41614684 -0.9899925 ]
[-2.18503986 -3.38051501  0.64836083]
2.0


In [25]:
x=np.array([[2,4],[5,11],[3,4]])
print(x.mean())
print(x.mean(axis=0))
print(x.mean(axis=1))
print(x.sum())
print(x.min(axis=0))
print(x.max(axis=1))

4.833333333333333
[3.33333333 6.33333333]
[3.  8.  3.5]
29
[2 4]
[ 4 11  4]
